package head.secretspace.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import head.secretspace.entity.Secretspace;
import head.secretspace.entity.SecretspaceUser;
import head.secretspace.entity.AddPwItem;
import head.secretspace.entity.AddMainValue;
import head.secretspace.entity.AddBankCard;
import head.secretspace.entity.AddIdentityCard;

import head.secretspace.dao.SecretspaceDao;
import head.secretspace.dao.SecretspaceUserDao;
import head.secretspace.dao.AddPwItemDao;
import head.secretspace.dao.AddMainValueDao;
import head.secretspace.dao.AddBankCardDao;
import head.secretspace.dao.AddIdentityCardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig secretspaceDaoConfig;
    private final DaoConfig secretspaceUserDaoConfig;
    private final DaoConfig addPwItemDaoConfig;
    private final DaoConfig addMainValueDaoConfig;
    private final DaoConfig addBankCardDaoConfig;
    private final DaoConfig addIdentityCardDaoConfig;

    private final SecretspaceDao secretspaceDao;
    private final SecretspaceUserDao secretspaceUserDao;
    private final AddPwItemDao addPwItemDao;
    private final AddMainValueDao addMainValueDao;
    private final AddBankCardDao addBankCardDao;
    private final AddIdentityCardDao addIdentityCardDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        secretspaceDaoConfig = daoConfigMap.get(SecretspaceDao.class).clone();
        secretspaceDaoConfig.initIdentityScope(type);

        secretspaceUserDaoConfig = daoConfigMap.get(SecretspaceUserDao.class).clone();
        secretspaceUserDaoConfig.initIdentityScope(type);

        addPwItemDaoConfig = daoConfigMap.get(AddPwItemDao.class).clone();
        addPwItemDaoConfig.initIdentityScope(type);

        addMainValueDaoConfig = daoConfigMap.get(AddMainValueDao.class).clone();
        addMainValueDaoConfig.initIdentityScope(type);

        addBankCardDaoConfig = daoConfigMap.get(AddBankCardDao.class).clone();
        addBankCardDaoConfig.initIdentityScope(type);

        addIdentityCardDaoConfig = daoConfigMap.get(AddIdentityCardDao.class).clone();
        addIdentityCardDaoConfig.initIdentityScope(type);

        secretspaceDao = new SecretspaceDao(secretspaceDaoConfig, this);
        secretspaceUserDao = new SecretspaceUserDao(secretspaceUserDaoConfig, this);
        addPwItemDao = new AddPwItemDao(addPwItemDaoConfig, this);
        addMainValueDao = new AddMainValueDao(addMainValueDaoConfig, this);
        addBankCardDao = new AddBankCardDao(addBankCardDaoConfig, this);
        addIdentityCardDao = new AddIdentityCardDao(addIdentityCardDaoConfig, this);

        registerDao(Secretspace.class, secretspaceDao);
        registerDao(SecretspaceUser.class, secretspaceUserDao);
        registerDao(AddPwItem.class, addPwItemDao);
        registerDao(AddMainValue.class, addMainValueDao);
        registerDao(AddBankCard.class, addBankCardDao);
        registerDao(AddIdentityCard.class, addIdentityCardDao);
    }
    
    public void clear() {
        secretspaceDaoConfig.clearIdentityScope();
        secretspaceUserDaoConfig.clearIdentityScope();
        addPwItemDaoConfig.clearIdentityScope();
        addMainValueDaoConfig.clearIdentityScope();
        addBankCardDaoConfig.clearIdentityScope();
        addIdentityCardDaoConfig.clearIdentityScope();
    }

    public SecretspaceDao getSecretspaceDao() {
        return secretspaceDao;
    }

    public SecretspaceUserDao getSecretspaceUserDao() {
        return secretspaceUserDao;
    }

    public AddPwItemDao getAddPwItemDao() {
        return addPwItemDao;
    }

    public AddMainValueDao getAddMainValueDao() {
        return addMainValueDao;
    }

    public AddBankCardDao getAddBankCardDao() {
        return addBankCardDao;
    }

    public AddIdentityCardDao getAddIdentityCardDao() {
        return addIdentityCardDao;
    }

}
