package head.secretspace.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADD_IDENTITY_CARD".
 */
@Entity
public class AddIdentityCard {

    @Id
    private Long id;
    private String name;
    private String gender;
    private String familyName;
    private String idCard;
    private String homeAddress;
    private String mechanism;
    private String startTime;
    private String endTime;
    private String time;
    private Integer like;

    @Generated
    public AddIdentityCard() {
    }

    public AddIdentityCard(Long id) {
        this.id = id;
    }

    @Generated
    public AddIdentityCard(Long id, String name, String gender, String familyName,
                           String idCard, String homeAddress, String mechanism,
                           String startTime, String endTime, String time, Integer like) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.familyName = familyName;
        this.idCard = idCard;
        this.homeAddress = homeAddress;
        this.mechanism = mechanism;
        this.startTime = startTime;
        this.endTime = endTime;
        this.time = time;
        this.like = like;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getFamilyName() {
        return familyName;
    }

    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getHomeAddress() {
        return homeAddress;
    }

    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    public String getMechanism() {
        return mechanism;
    }

    public void setMechanism(String mechanism) {
        this.mechanism = mechanism;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getLike() {
        return like;
    }

    public void setLike(Integer like) {
        this.like = like;
    }

}
