package head.secretspace.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADD_MAIN_VALUE".
 */
@Entity
public class AddMainValue {

    @Id
    private Long id;
    private String sqlName;
    private Integer value;
    private String time;
    private Integer like;

    @Generated
    public AddMainValue() {
    }

    public AddMainValue(Long id) {
        this.id = id;
    }

    @Generated
    public AddMainValue(Long id, String sqlName, Integer value, String time, Integer like) {
        this.id = id;
        this.sqlName = sqlName;
        this.value = value;
        this.time = time;
        this.like = like;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSqlName() {
        return sqlName;
    }

    public void setSqlName(String sqlName) {
        this.sqlName = sqlName;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getLike() {
        return like;
    }

    public void setLike(Integer like) {
        this.like = like;
    }

}
