package head.secretspace.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ADD_PW_ITEM".
 */
@Entity
public class AddPwItem {

    @Id
    private Long id;
    private String name;
    private String password;
    private String remarks;
    private String time;
    private Integer like;

    @Generated
    public AddPwItem() {
    }

    public AddPwItem(Long id) {
        this.id = id;
    }

    @Generated
    public AddPwItem(Long id, String name, String password, String remarks, String time, Integer like) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.remarks = remarks;
        this.time = time;
        this.like = like;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getLike() {
        return like;
    }

    public void setLike(Integer like) {
        this.like = like;
    }

}
