package head.secretspace.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SECRETSPACE_USER".
 */
@Entity
public class SecretspaceUser {

    @Id
    private Long id;
    private String password;
    private String time;

    @Generated
    public SecretspaceUser() {
    }

    public SecretspaceUser(Long id) {
        this.id = id;
    }

    @Generated
    public SecretspaceUser(Long id, String password, String time) {
        this.id = id;
        this.password = password;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
